sudo: required

services:
  - docker

before_install:
  - docker build -t aarish13111/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aarish13111/docker-react npm run test -- --coverage --verbose
#  - docker run aarish13111/docker-react npm run test -- --coverage

deploy:
  providers: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-303602097774"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
